spring:
  application:
    name: message-worker

  rabbitmq:
    host: localhost
    port: 5672
    username: maiload
    password: maiload

  kafka:
    bootstrap-servers: localhost:9094
    consumer:
      group-id: message-worker
      auto-offset-reset: earliest
    producer:
      acks: all
      retries: 3

server:
  port: 8082

worker:
  rabbitmq:
    queue: message.realtime.queue
    exchange: message.exchange
    dlq-routing-key: dlq
    retry:
      routing-keys: retry.5s,retry.30s,retry.2m
  kafka:
    cdr-topic: cdr.events
    bulk-task-topic: bulk.send.task
  minio:
    endpoint: http://localhost:9000
    access-key: maiload
    secret-key: maiload123
    bucket: message-receiver
