plugins {
    id 'org.springframework.boot'
}

ext {
    set('springCloudVersion', '2024.0.1')
}

dependencies {
    implementation project(':common')

    // Spring Boot
    implementation 'org.springframework.boot:spring-boot-starter'
    implementation 'org.springframework.boot:spring-boot-starter-validation'

    // RabbitMQ
    implementation 'org.springframework.boot:spring-boot-starter-amqp'

    // Kafka
    implementation 'org.springframework.kafka:spring-kafka'

    // HTTP Client (Gateway)
    implementation 'org.springframework.boot:spring-boot-starter-webmvc'

    // Resilience
    implementation 'org.springframework.cloud:spring-cloud-starter-circuitbreaker-resilience4j'

    // Observability
    implementation 'org.springframework.boot:spring-boot-starter-actuator'
    runtimeOnly 'io.micrometer:micrometer-registry-prometheus'

    // Test
    testImplementation 'org.springframework.boot:spring-boot-starter-amqp-test'
    testImplementation 'org.springframework.kafka:spring-kafka-test'
    testImplementation 'org.testcontainers:junit-jupiter'
    testImplementation 'org.testcontainers:kafka'
    testImplementation 'org.testcontainers:rabbitmq'
}

dependencyManagement {
    imports {
        mavenBom "org.springframework.cloud:spring-cloud-dependencies:${springCloudVersion}"
    }
}
